export const LOGIN = "LOGIN";
export const AUTO_LOGIN = "AUTO_LOGIN";
export const LOGOUT = "LOGOUT";

export const LOAD_PROJECTS_PAGE_1 = "LOAD_PROJECTS_PAGE_1";
export const LOAD_PROJECTS_NEXT_PAGES = "LOAD_PROJECTS_NEXT_PAGES";
export const LOAD_COMPLETED_PROJECTS = "LOAD_COMPLETED_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const COMPLETE_PROJECT = "COMPLETE_PROJECT";
// export const RESTORE_PROJECT = "RESTORE_PROJECT";
